# Generated by Django 3.2.9 on 2021-11-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('entry', models.CharField(max_length=350)),
                ('img', models.CharField(max_length=250)),
                ('video_url', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='Post Date')),
            ],
        ),
    ]
