# Generated by Django 3.2.9 on 2021-12-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentries',
            old_name='entry',
            new_name='future',
        ),
    ]
