# Generated by Django 3.2.9 on 2021-12-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_entry_userentries_future'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentries',
            old_name='future',
            new_name='in_the_future',
        ),
        migrations.RenameField(
            model_name='userentries',
            old_name='img',
            new_name='optional_image',
        ),
        migrations.RenameField(
            model_name='userentries',
            old_name='video',
            new_name='optional_video',
        ),
        migrations.RenameField(
            model_name='userentries',
            old_name='title',
            new_name='title_of_that_future',
        ),
    ]
