# Generated by Django 3.2.9 on 2021-12-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentries',
            name='title_of_that_future',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('userentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.userentries')),
            ],
        ),
    ]
