# Generated by Django 3.2.9 on 2021-11-30 14:59

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_allentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentries',
            name='video_url',
        ),
        migrations.AddField(
            model_name='userentries',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='userentries',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
