# Generated by Django 3.2.9 on 2021-11-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211130_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentries',
            name='video',
        ),
    ]
