# Generated by Django 3.2.9 on 2021-11-30 18:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_userentries_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentries',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
