# Generated by Django 3.2.9 on 2021-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userentries',
            name='in_the_future',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userentries',
            name='title_of_that_future',
            field=models.CharField(max_length=350),
        ),
    ]
