# Generated by Django 3.2.9 on 2021-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userentries_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentries',
            name='img',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
