# Generated by Django 3.2.9 on 2021-12-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211201_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userentry',
            new_name='userentries',
        ),
    ]
