# Generated by Django 3.2.9 on 2021-12-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_userentry_comment_userentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userentries',
            new_name='userentry',
        ),
    ]
