# Generated by Django 3.2.9 on 2021-12-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_userentries_comment_userentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userentry',
            new_name='post',
        ),
    ]
