# Generated by Django 3.2.9 on 2021-12-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_userentry_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='entry',
        ),
    ]
