# Generated by Django 3.2.9 on 2021-12-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_userentries_relevant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentries',
            name='relevant_link',
            field=models.URLField(blank=True, max_length=350),
        ),
    ]
